name: Run Telegram Bot and Price Action Notebook

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - main

jobs:
  run_bot_and_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert ipykernel

      - name: Install TA-Lib system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libta-lib-dev

      - name: Find TA-Lib include directory (if needed)
        run: |
          TA_LIB_INCLUDE=$(find /usr /usr/local /opt /opt/local /opt/homebrew -name ta-lib -type d 2>/dev/null)
          echo "TA_LIB_INCLUDE=${TA_LIB_INCLUDE}"
          if [ -n "$TA_LIB_INCLUDE" ]; then
            echo "TA_LIB_INCLUDE_PATH=${TA_LIB_INCLUDE}" >> $GITHUB_ENV
          fi

      - name: Install TA-Lib Python wrapper with include path
        run: |
          pip install TA-Lib --global-option=build_ext --global-option="-I$TA_LIB_INCLUDE_PATH/include"
        env:
          TA_LIB_INCLUDE_PATH: "" # Initialize in case find doesn't find it
        continue-on-error: true

      - name: Run Price Action Notebook
        run: |
          jupyter nbconvert --execute PRICEACTION.ipynb --to notebook --output executed_PRICEACTION.ipynb
        continue-on-error: true

      - name: Run the bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
