name: Run Telegram Bot and Price Action Notebook

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  run_bot_and_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert ipykernel

      - name: Set up TA-Lib (Linux - adjust if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y libta-lib-dev
          pip install TA-Lib

      - name: Run Price Action Notebook
        run: |
          jupyter nbconvert --execute PRICEACTION.ipynb --to notebook --output executed_PRICEACTION.ipynb
        continue-on-error: true

      - name: Run the bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
