name: Run Telegram Bot and Price Action Notebook

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  push:
    branches:
      - main # Runs on push to main branch

jobs:
  run_bot_and_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Pin a specific minor version for consistency

      - name: Install base Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert ipykernel # For notebook execution

      # --- Install TA-Lib C Library using apt ---
      - name: Install TA-Lib C library development package
        run: |
          sudo apt-get update
          sudo apt-get install -y libta-lib-dev # Install the dev package

      # --- Install TA-Lib Python wrapper ---
      - name: Install TA-Lib Python wrapper
        # No need to set TA_INCLUDE_PATH or TA_LIBRARY_PATH
        # pip install should now find the C library in standard system locations
        run: |
          pip install TA-Lib --no-cache-dir --verbose

      - name: Verify TA-Lib Python Import (Optional but recommended)
        run: python -c "import talib; print(f'TA-Lib version: {talib.__version__}')"

      - name: Run Price Action Notebook
        run: |
          jupyter nbconvert --execute PRICEACTION.ipynb --to notebook --output executed_PRICEACTION.ipynb

      - name: Run the bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
